# <center>Naive Bayes<center>

1. Multinomial naive bayes
2. Gaussian naive bayes

---

Importing libraries

In [1]:
import numpy as np
import pandas as pd

Importing data

In [2]:
import os

data = os.path.abspath('../data/spam.csv')
df = pd.read_csv(data, encoding='latin-1')

df = pd.DataFrame({'sms': df['v2'],'result': df['v1']})

---

Chcecking data

In [3]:
df.head()

                                                 sms result
0  Go until jurong point, crazy.. Available only ...    ham
1                      Ok lar... Joking wif u oni...    ham
2  Free entry in 2 a wkly comp to win FA Cup fina...   spam
3  U dun say so early hor... U c already then say...    ham
4  Nah I don't think he goes to usf, he lives aro...    ham

---

### **Multinomial NB**

In [11]:
from multinomial_nb import Multinomial_nb

X = df['sms']
y = df['result']

multi_nb = Multinomial_nb()

multi_nb.fit(X, y)

X_predict = df['sms']
y_pred = multi_nb.predict(X_predict)

print(y_pred)

['ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'spam', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'spam', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'spam', 'ham

---

### **Gaussian NB**

In [5]:
data = os.path.abspath('../data/iris/iris.data')
iris = pd.read_csv(data, header=None)

iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
from gaussian_nb import Gaussian_nb

X = iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = iris['class']

gauss_nb = Gaussian_nb()
gauss_nb.fit(X, y)

y_pred = gauss_nb.predict(X)
y_pred

[[np.float64(1.006783168089317),
  np.float64(-39.32757785099671),
  np.float64(-55.77146507797407)],
 [np.float64(0.4185314218363525),
  np.float64(-37.59288873341325),
  np.float64(-55.23006609414038)],
 [np.float64(0.14635674250854147),
  np.float64(-40.43373346920053),
  np.float64(-57.736331817523876)],
 [np.float64(0.1003990160334205),
  np.float64(-37.94011213407826),
  np.float64(-55.32009601206887)],
 [np.float64(0.9512740635993426),
  np.float64(-40.45224402574391),
  np.float64(-56.70565976185485)],
 [np.float64(-2.1907255526236256),
  np.float64(-33.40392066189565),
  np.float64(-49.05295262951795)],
 [np.float64(0.3488513738405137),
  np.float64(-37.92355906690885),
  np.float64(-55.1085388770027)],
 [np.float64(1.110739768459817),
  np.float64(-37.69699889343279),
  np.float64(-54.347422683318776)],
 [np.float64(-1.336435274817958),
  np.float64(-39.823458659374495),
  np.float64(-57.64962317431244)],
 [np.float64(-0.09931396031650652),
  np.float64(-39.61189198669689),
  np.float64(-56.44338846948981)],
 [np.float64(0.21342174509205925),
  np.float64(-38.96840228316859),
  np.float64(-54.63580379544726)],
 [np.float64(0.6544584425265942),
  np.float64(-37.247417024142166),
  np.float64(-53.86845062080853)],
 [np.float64(-0.5248496337488189),
  np.float64(-41.00769818343369),
  np.float64(-58.14688596818088)],
 [np.float64(-4.492331380381345),
  np.float64(-47.69810225638812),
  np.float64(-64.9042269730828)],
 [np.float64(-3.727536615891972),
  np.float64(-45.70783431807307),
  np.float64(-60.32394807486942)],
 [np.float64(-5.1217620002214375),
  np.float64(-42.385785280845035),
  np.float64(-56.53142124959691)],
 [np.float64(-1.7124175265932569),
  np.float64(-38.40355097612856),
  np.float64(-54.37424336708227)],
 [np.float64(0.9545814635438623),
  np.float64(-36.57609053234521),
  np.float64(-53.41704702700281)],
 [np.float64(-2.284424627217086),
  np.float64(-34.368274569722956),
  np.float64(-49.66238896420922)],
 [np.float64(0.5216774082199074),
  np.float64(-37.98457596998228),
  np.float64(-54.02023218464271)],
 [np.float64(-0.41728336023955326),
  np.float64(-34.18278708199632),
  np.float64(-50.37934769352407)],
 [np.float64(-0.1718704259033984),
  np.float64(-34.49356992552794),
  np.float64(-51.05225815422234)],
 [np.float64(-3.219502648166479),
  np.float64(-47.700809077945394),
  np.float64(-64.18972155796801)],
 [np.float64(-2.641672593139657),
  np.float64(-26.87888073130055),
  np.float64(-44.34499689624234)],
 [np.float64(-2.195460212571018),
  np.float64(-33.837343086988746),
  np.float64(-50.12371702303838)],
 [np.float64(0.22444820150209166),
  np.float64(-34.722998816813984),
  np.float64(-52.164318972955726)],
 [np.float64(-0.1493482319345837),
  np.float64(-31.222474365625242),
  np.float64(-48.45724811129645)],
 [np.float64(0.9373890132500529),
  np.float64(-37.76001813385537),
  np.float64(-54.06908798425161)],
 [np.float64(0.9129285095478903),
  np.float64(-38.341999017461816),
  np.float64(-54.95815195341207)],
 [np.float64(0.28586325010073144),
  np.float64(-36.616080973821596),
  np.float64(-53.696116873270014)],
 [np.float64(0.307302210976649),
  np.float64(-35.78503360445305),
  np.float64(-53.072328019654734)],
 [np.float64(-0.488244462586231),
  np.float64(-31.34476902368969),
  np.float64(-48.39806302287396)],
 [np.float64(-1.4591719823915783),
  np.float64(-47.04328206349156),
  np.float64(-61.32127221738439)],
 [np.float64(-2.0226408675097525),
  np.float64(-46.05025288537445),
  np.float64(-60.39322133440642)],
 [np.float64(-0.09931396031650652),
  np.float64(-39.61189198669689),
  np.float64(-56.44338846948981)],
 [np.float64(-0.1877990763896641),
  np.float64(-40.5740342242824),
  np.float64(-57.85923293636155)],
 [np.float64(-0.3183639988174556),
  np.float64(-39.69057727026905),
  np.float64(-55.87686845785504)],
 [np.float64(-0.09931396031650652),
  np.float64(-39.61189198669689),
  np.float64(-56.44338846948981)],
 [np.float64(-1.3927364375575257),
  np.float64(-41.32409392509811),
  np.float64(-59.00611673235939)],
 [np.float64(1.0753270027819488),
  np.float64(-37.364457071017206),
  np.float64(-53.96705241763195)],
 [np.float64(0.611333708614356),
  np.float64(-38.226469693023276),
  np.float64(-55.17698686816132)],
 [np.float64(-4.7004493608275135),
  np.float64(-38.86792415644635),
  np.float64(-58.30362314204602)],
 [np.float64(-0.9546583358397376),
  np.float64(-41.99435299245563),
  np.float64(-59.248414915319245)],
 [np.float64(-4.625935351975271),
  np.float64(-27.688641850603336),
  np.float64(-44.868929274700164)],
 [np.float64(-3.5361275427266508),
  np.float64(-30.85146482367281),
  np.float64(-46.73974206582149)],
 [np.float64(0.2407753662511809),
  np.float64(-35.24900911131178),
  np.float64(-53.30548128228726)],
 [np.float64(0.28822293055278014),
  np.float64(-39.50879896331031),
  np.float64(-55.06074318158309)],
 [np.float64(0.23849579535861332),
  np.float64(-39.59856970162253),
  np.float64(-56.836058454601655)],
 [np.float64(0.4902851858463062),
  np.float64(-39.188345294382515),
  np.float64(-54.94197960098711)],
 [np.float64(1.0173990600850458),
  np.float64(-38.380534181184316),
  np.float64(-55.33263672508235)],
 [np.float64(-246.99178450099274),
  np.float64(-4.1498974767069345),
  np.float64(-5.547890889637604)],
 [np.float64(-228.4710064426076),
  np.float64(-2.4385252967283115),
  np.float64(-5.243207459466764)],
 [np.float64(-278.2659308947305),
  np.float64(-4.18958692814007),
  np.float64(-4.031761575152193)],
 [np.float64(-159.38948605977004),
  np.float64(-2.2182176131875133),
  np.float64(-12.398748634325079)],
 [np.float64(-241.03527277194647),
  np.float64(-1.8284749438806718),
  np.float64(-4.780112699873392)],
 [np.float64(-203.62588820169125),
  np.float64(-0.826254577265172),
  np.float64(-7.734357844738805)],
 [np.float64(-259.4691314975766),
  np.float64(-3.6513486551533525),
  np.float64(-4.311308934510827)],
 [np.float64(-83.24277376272444),
  np.float64(-6.733049658758266),
  np.float64(-21.7134668335118)],
 [np.float64(-221.77164253228398),
  np.float64(-1.7617133372574862),
  np.float64(-6.311247315961162)],
 [np.float64(-157.39467221042247),
  np.float64(-1.9830187164744304),
  np.float64(-11.124063843621215)],
 [np.float64(-99.41471790828734),
  np.float64(-7.899487402507813),
  np.float64(-22.87211386749527)],
 [np.float64(-195.54715494112656),
  np.float64(-1.2443902352838672),
  np.float64(-6.726424097157875)],
 [np.float64(-139.54062306220226),
  np.float64(-3.747416415860606),
  np.float64(-15.542528252820059)],
 [np.float64(-236.56822669104054),
  np.float64(-1.2227703795535796),
  np.float64(-5.413250408670049)],
 [np.float64(-125.40979981616186),
  np.float64(-1.8707572728670558),
  np.float64(-12.285242924289067)],
 [np.float64(-211.97281282757115),
  np.float64(-2.3408450002877466),
  np.float64(-6.171184973526616)],
 [np.float64(-222.50903198363423),
  np.float64(-1.5760975915866209),
  np.float64(-6.1642784116114875)],
 [np.float64(-143.3573901000548),
  np.float64(-2.0544680006418097),
  np.float64(-12.870576071805298)],
 [np.float64(-231.3336906477753),
  np.float64(-2.8761663438944796),
  np.float64(-8.020172812274337)],
 [np.float64(-133.53251585223728),
  np.float64(-2.10662643123357),
  np.float64(-13.754222772345688)],
 [np.float64(-292.31284042770494),
  np.float64(-5.052319302242023),
  np.float64(-3.4010394764771057)],
 [np.float64(-160.2343218971917),
  np.float64(-0.7948504011231218),
  np.float64(-9.191062403222684)],
 [np.float64(-273.1225613625559),
  np.float64(-2.5114767879207958),
  np.float64(-5.017761662693449)],
 [np.float64(-218.58446625358096),
  np.float64(-1.274498362343352),
  np.float64(-7.457372337667665)],
 [np.float64(-189.61204868921743),
  np.float64(-1.0802087202630652),
  np.float64(-7.440176211997529)],
 [np.float64(-210.90314228134778),
  np.float64(-1.7885074980215614),
  np.float64(-6.082777396584539)],
 [np.float64(-256.00946775981953),
  np.float64(-2.713865813616729),
  np.float64(-5.030263626046953)],
 [np.float64(-310.80587055870956),
  np.float64(-4.9704574414594465),
  np.float64(-2.52669749149931)],
 [np.float64(-225.38754915497728),
  np.float64(-1.1891204864797917),
  np.float64(-5.407817967758679)],
 [np.float64(-96.7322778641285),
  np.float64(-3.496052127119161),
  np.float64(-16.840574292646284)],
 [np.float64(-125.83614741135423),
  np.float64(-2.7621523381022506),
  np.float64(-15.07355004235596)],
 [np.float64(-111.23057852084942),
  np.float64(-3.6988853611969033),
  np.float64(-16.959038739900365)],
 [np.float64(-141.40520488017708),
  np.float64(-1.1341285889017307),
  np.float64(-11.434488229792782)],
 [np.float64(-304.08629512567916),
  np.float64(-3.16827098759894),
  np.float64(-3.6300472771053833)],
 [np.float64(-221.71385442704934),
  np.float64(-1.9033848028127978),
  np.float64(-6.702435562544215)],
 [np.float64(-235.8271254350916),
  np.float64(-3.6914544992306304),
  np.float64(-5.622912147058934)],
 [np.float64(-253.2165756147433),
  np.float64(-3.0519235057478573),
  np.float64(-4.4206822327127915)],
 [np.float64(-201.49708013189888),
  np.float64(-2.001435138907112),
  np.float64(-9.26201302573537)],
 [np.float64(-164.71393178150444),
  np.float64(-1.1251818177034278),
  np.float64(-9.468226619557289)],
 [np.float64(-157.9870850926357),
  np.float64(-1.4667150225139371),
  np.float64(-11.294945800841305)],
 [np.float64(-184.98812909893098),
  np.float64(-1.3289506883303366),
  np.float64(-10.140487124704647)],
 [np.float64(-225.66330225725076),
  np.float64(-1.2289509317836647),
  np.float64(-5.686312362943415)],
 [np.float64(-150.1916614681148),
  np.float64(-1.1156057038203713),
  np.float64(-11.22005766828588)],
 [np.float64(-83.93334355594696),
  np.float64(-6.7895033966847835),
  np.float64(-21.908341534152758)],
 [np.float64(-174.80942378799773),
  np.float64(-0.8316360906387914),
  np.float64(-9.365610614340707)],
 [np.float64(-165.40153342075257),
  np.float64(-1.1623654310370934),
  np.float64(-9.804683210324656)],
 [np.float64(-174.47637857407491),
  np.float64(-0.7852245331135808),
  np.float64(-8.799027016288983)],
 [np.float64(-187.52913419889188),
  np.float64(-0.8069689384136868),
  np.float64(-7.582629575479721)],
 [np.float64(-72.77821491744656),
  np.float64(-6.5077278089298),
  np.float64(-21.496119703132432)],
 [np.float64(-165.9458448177433),
  np.float64(-0.7537961669139703),
  np.float64(-9.378547381617024)],
 [np.float64(-568.6833050765058),
  np.float64(-26.730799194681968),
  np.float64(-3.735508169327156)],
 [np.float64(-341.9551326249512),
  np.float64(-6.447982313183905),
  np.float64(-2.872684659197861)],
 [np.float64(-493.69247374296907),
  np.float64(-17.13911576109732),
  np.float64(-1.8658098091838806)],
 [np.float64(-395.87072647048547),
  np.float64(-7.851023661090816),
  np.float64(-1.7745303883655543)],
 [np.float64(-487.0434997056598),
  np.float64(-16.58043979357529),
  np.float64(-1.61777318531322)],
 [np.float64(-614.4048376719904),
  np.float64(-26.101104762951405),
  np.float64(-4.412214851849783)],
 [np.float64(-247.03014209747664),
  np.float64(-4.881298736507352),
  np.float64(-8.42802593529172)],
 [np.float64(-514.6138423498145),
  np.float64(-16.451263139040776),
  np.float64(-3.213516830408187)],
 [np.float64(-430.79911892765773),
  np.float64(-10.2863704392552),
  np.float64(-2.8384608825890085)],
 [np.float64(-596.614911388649),
  np.float64(-32.36280047459032),
  np.float64(-5.632615960801609)],
 [np.float64(-361.6311438480752),
  np.float64(-9.519873421026606),
  np.float64(-1.8982850655692078)],
 [np.float64(-372.05694541297595),
  np.float64(-7.66869273555199),
  np.float64(-1.917414652691682)],
 [np.float64(-432.7177615565775),
  np.float64(-13.388861042869161),
  np.float64(-1.402864799986991)],
 [np.float64(-345.4147012767349),
  np.float64(-8.100973222383162),
  np.float64(-3.8631978659600286)],
 [np.float64(-424.40872024410186),
  np.float64(-16.96310614689408),
  np.float64(-3.4792337170636056)],
 [np.float64(-435.0360577145461),
  np.float64(-16.499601274851216),
  np.float64(-2.1944375740631514)],
 [np.float64(-384.22025848104914),
  np.float64(-7.79793131107922),
  np.float64(-1.6591206061043393)],
 [np.float64(-650.2421090416628),
  np.float64(-35.05219572072442),
  np.float64(-8.476530001893739)],
 [np.float64(-704.9447243447346),
  np.float64(-34.47534437321581),
  np.float64(-6.98536192852914)],
 [np.float64(-284.1463275275444),
  np.float64(-3.8625777188167634),
  np.float64(-6.9450185677306555)],
 [np.float64(-495.2754504632657),
  np.float64(-20.0857378490383),
  np.float64(-2.2028161605832386)],
 [np.float64(-331.7303471150955),
  np.float64(-7.530244672833582),
  np.float64(-3.358244695187496)],
 [np.float64(-618.759440911345),
  np.float64(-25.711352850038544),
  np.float64(-5.145836130784554)],
 [np.float64(-308.6934795095666),
  np.float64(-4.651736120267361),
  np.float64(-2.803185492653901)],
 [np.float64(-458.236470281866),
  np.float64(-15.454741515778485),
  np.float64(-1.9019901851436705)],
 [np.float64(-465.35253279944266),
  np.float64(-14.243392423975433),
  np.float64(-2.680023736561447)],
 [np.float64(-295.9852624976283),
  np.float64(-4.24638142887721),
  np.float64(-2.9018772053791375)],
 [np.float64(-305.5978134483374),
  np.float64(-4.697292782500612),
  np.float64(-2.637423559483819)],
 [np.float64(-441.87171903464076),
  np.float64(-12.712140717043097),
  np.float64(-1.5326391686016771)],
 [np.float64(-410.98629469134),
  np.float64(-10.174991971972823),
  np.float64(-3.0735671463486036)],
 [np.float64(-499.4022337247315),
  np.float64(-16.483562533289707),
  np.float64(-2.862383002518926)],
 [np.float64(-571.7633544791629),
  np.float64(-29.381781169138993),
  np.float64(-7.896851789664574)],
 [np.float64(-458.4544605119135),
  np.float64(-14.819227659950938),
  np.float64(-1.6970242127010224)],
 [np.float64(-295.0258000586127),
  np.float64(-2.816121228747126),
  np.float64(-3.720725838637817)],
 [np.float64(-348.1387974894256),
  np.float64(-4.911152190247649),
  np.float64(-4.871543883698493)],
 [np.float64(-569.4220490691755),
  np.float64(-26.481867698855336),
  np.float64(-3.8262346101754297)],
 [np.float64(-491.83409536423613),
  np.float64(-21.655935692837584),
  np.float64(-3.209255540015789)],
 [np.float64(-382.804596745153),
  np.float64(-7.8893643461599146),
  np.float64(-1.7663241129503158)],
 [np.float64(-293.5106833203297),
  np.float64(-4.387314846073922),
  np.float64(-3.000954408271352)],
 [np.float64(-420.7085673323168),
  np.float64(-13.477354992282732),
  np.float64(-1.574223236295205)],
 [np.float64(-496.99094904330747),
  np.float64(-21.040295333385),
  np.float64(-2.3260781056228725)],
 [np.float64(-417.01753314280774),
  np.float64(-16.602234070773136),
  np.float64(-2.33301313057191)],
 [np.float64(-341.9551326249512),
  np.float64(-6.447982313183905),
  np.float64(-2.872684659197861)],
 [np.float64(-522.5961058814029),
  np.float64(-21.137511203504513),
  np.float64(-2.3008627185614543)],
 [np.float64(-529.7876066455024),
  np.float64(-25.41737589632331),
  np.float64(-3.35494186524756)],
 [np.float64(-426.6266190550613),
  np.float64(-16.072362494223878),
  np.float64(-2.023095903623093)],
 [np.float64(-335.37205603816227),
  np.float64(-6.649441627451281),
  np.float64(-3.091423138434423)],
 [np.float64(-374.3125787827649),
  np.float64(-9.252664261247654),
  np.float64(-1.5240052145132998)],
 [np.float64(-445.698259476985),
  np.float64(-17.79646109745722),
  np.float64(-2.8974702642624277)],
 [np.float64(-327.48803891987825),
  np.float64(-5.319490918803179),
  np.float64(-2.565808724906618)]]

In [9]:
classes = gauss_nb.predict_class(X)

classes

['Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica']

---